views:
  - title: Home
    type: custom:grid-layout
    badges: []
    cards:
  - type: horizontal-stack
        cards:
  - type: gauge
    entity: sensor.bedroom_temp_temperature
    name: Bedroom
    theme: minimalist-mobile
    needle: true
    min: -5
    max: 3
    segments:
     - from: -5
       color: '#0000FF'
     - from: 0
       color: '#3366FF'
     - from: 5
       color: '#6699FF'
     - from: 10
       color: '#99CCFF'
     - from: 15
       color: '#CCE5FF'
     - from: 20
       color: '#FFA500'
     - from: 25
       color: '#FF8000'
     - from: 30
       color: '#FF4000'
     - from: 35
       color: '#FF0000'
     - type: gauge
       
