views:
  - title: Home
    type: custom:grid-layout
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            entity: sensor.bedroom_temp_temperature
            name: Bedroom
            theme: minimalist-mobile
            needle: true
            min: -5
            max: 39
            segments:
              - from: -5
                color: '#0000FF'
              - from: 0
                color: '#3366FF'
              - from: 5
                color: '#6699FF'
              - from: 10
                color: '#99CCFF'
              - from: 15
                color: '#CCE5FF'
              - from: 20
                color: '#FFA500'
              - from: 25
                color: '#FF8000'
              - from: 30
                color: '#FF4000'
              - from: 35
                color: '#FF0000'
          - type: gauge
            entity: sensor.office_temp_temperature
            name: Office
            theme: minimalist-mobile
            needle: true
            min: -5
            max: 40
            segments:
              - from: -5
                color: '#0000FF'
              - from: 0
                color: '#3366FF'
              - from: 5
                color: '#6699FF'
              - from: 10
                color: '#99CCFF'
              - from: 15
                color: '#CCE5FF'
              - from: 20
                color: '#FFA500'
              - from: 25
                color: '#FF8000'
              - from: 30
                color: '#FF4000'
              - from: 35
                color: '#FF0000'
          - type: gauge
            name: Sunroom
            theme: minimalist-mobile
            needle: true
            min: -5
            max: 40
            entity: sensor.sunroom_temp_temperature
            segments:
              - from: -5
                color: '#0000FF'
              - from: 0
                color: '#3366FF'
              - from: 5
                color: '#6699FF'
              - from: 10
                color: '#99CCFF'
              - from: 15
                color: '#CCE5FF'
              - from: 20
                color: '#FFA500'
              - from: 25
                color: '#FF8000'
              - from: 30
                color: '#FF4000'
              - from: 35
                color: '#FF0000'
          - type: gauge
            entity: sensor.lounge_temp_temperature
            name: Lounge
            theme: minimalist-mobile
            needle: true
            min: -5
            max: 40
            segments:
              - from: -5
                color: '#0000FF'
              - from: 0
                color: '#3366FF'
              - from: 5
                color: '#6699FF'
              - from: 10
                color: '#99CCFF'
              - from: 15
                color: '#CCE5FF'
              - from: 20
                color: '#FFA500'
              - from: 25
                color: '#FF8000'
              - from: 30
                color: '#FF4000'
              - from: 35
                color: '#FF0000'
          - type: gauge
            entity: sensor.temperature
            name: Inverter
            theme: minimalist-mobile
            min: 0
            max: 80
            needle: true
            segments:
              - from: 0
                color: '#0000FF'
              - from: 5
                color: '#0026FF'
              - from: 10
                color: '#004CFF'
              - from: 15
                color: '#0073FF'
              - from: 20
                color: '#0099FF'
              - from: 25
                color: '#00BFFF'
              - from: 30
                color: '#00E5E5'
              - from: 35
                color: '#00FFCC'
              - from: 40
                color: '#00FF99'
              - from: 45
                color: '#00FF66'
              - from: 50
                color: '#FFBF00'
              - from: 55
                color: '#FF8000'
              - from: 60
                color: '#FF0000'
      - type: horizontal-stack
        cards:
          - type: gauge
            name: Balancell
            needle: true
            min: 0
            max: 100
            segments:
              - from: 0
                color: '#FF0000'
              - from: 10
                color: '#FF1A00'
              - from: 15
                color: '#FF3300'
              - from: 20
                color: '#FF4D00'
              - from: 25
                color: '#FF6600'
              - from: 30
                color: '#FF8000'
              - from: 35
                color: '#FF9900'
              - from: 40
                color: '#FFB300'
              - from: 45
                color: '#FFCC00'
              - from: 50
                color: '#FFE500'
              - from: 55
                color: '#FFFF00'
              - from: 60
                color: '#E5FF00'
              - from: 65
                color: '#CCFF00'
              - from: 70
                color: '#B3FF00'
              - from: 75
                color: '#99FF00'
              - from: 80
                color: '#80FF00'
              - from: 85
                color: '#66FF00'
              - from: 90
                color: '#4DFF00'
              - from: 95
                color: '#00FF00'
            entity: sensor.battery_state_of_charge
          - type: gauge
            needle: true
            min: 0
            segments:
              - from: 0
                color: '#FF0000'
              - from: 10
                color: '#FF1A00'
              - from: 15
                color: '#FF3300'
              - from: 20
                color: '#FF4D00'
              - from: 25
                color: '#FF6600'
              - from: 30
                color: '#FF8000'
              - from: 35
                color: '#FF9900'
              - from: 40
                color: '#FFB300'
              - from: 45
                color: '#FFCC00'
              - from: 50
                color: '#FFE500'
              - from: 55
                color: '#FFFF00'
              - from: 60
                color: '#E5FF00'
              - from: 65
                color: '#CCFF00'
              - from: 70
                color: '#B3FF00'
              - from: 75
                color: '#99FF00'
              - from: 80
                color: '#80FF00'
              - from: 85
                color: '#66FF00'
              - from: 90
                color: '#4DFF00'
              - from: 95
                color: '#00FF00'
            entity: sensor.load_power
            name: Battery load
            max: 8000
          - type: gauge
            name: Nick's iPhone
            needle: true
            min: 0
            segments:
              - from: 0
                color: '#FF0000'
              - from: 10
                color: '#FF1A00'
              - from: 15
                color: '#FF3300'
              - from: 20
                color: '#FF4D00'
              - from: 25
                color: '#FF6600'
              - from: 30
                color: '#FF8000'
              - from: 35
                color: '#FF9900'
              - from: 40
                color: '#FFB300'
              - from: 45
                color: '#FFCC00'
              - from: 50
                color: '#FFE500'
              - from: 55
                color: '#FFFF00'
              - from: 60
                color: '#E5FF00'
              - from: 65
                color: '#CCFF00'
              - from: 70
                color: '#B3FF00'
              - from: 75
                color: '#99FF00'
              - from: 80
                color: '#80FF00'
              - from: 85
                color: '#66FF00'
              - from: 90
                color: '#4DFF00'
              - from: 95
                color: '#00FF00'
            entity: sensor.nicks_iphone_2_battery_level
            max: 100
          - type: gauge
            name: Solar PV
            needle: true
            min: 0
            segments:
              - from: 0
                color: '#FFFF00'
              - from: 500
                color: '#FFF600'
              - from: 1000
                color: '#FFED00'
              - from: 1500
                color: '#FFE400'
              - from: 2000
                color: '#FFDB00'
              - from: 2500
                color: '#FFD200'
              - from: 3000
                color: '#FFC900'
              - from: 3500
                color: '#FFC000'
              - from: 4000
                color: '#FFB700'
              - from: 4500
                color: '#FFAE00'
              - from: 5000
                color: '#FFA500'
              - from: 5500
                color: '#FF9C00'
              - from: 6000
                color: '#FF9300'
              - from: 6500
                color: '#FF8A00'
              - from: 7000
                color: '#FF8100'
              - from: 7500
                color: '#FF7800'
            entity: sensor.pv_power
            max: 8000
          - type: gauge
            name: Eskom
            needle: true
            min: 0
            segments:
              - from: 0
                color: '#FFFF00'
              - from: 500
                color: '#FFF600'
              - from: 1000
                color: '#FFED00'
              - from: 1500
                color: '#FFE400'
              - from: 2000
                color: '#FFDB00'
              - from: 2500
                color: '#FFD200'
              - from: 3000
                color: '#FFC900'
              - from: 3500
                color: '#FFC000'
              - from: 4000
                color: '#FFB700'
              - from: 4500
                color: '#FFAE00'
              - from: 5000
                color: '#FFA500'
              - from: 5500
                color: '#FF9C00'
              - from: 6000
                color: '#FF9300'
              - from: 6500
                color: '#FF8A00'
              - from: 7000
                color: '#FF8100'
              - from: 7500
                color: '#FF7800'
            entity: sensor.grid_power
            max: 8000
      - type: horizontal-stack
        cards:
          - type: custom:clock-weather-card
            entity: weather.forecast_bushwillow
            name: Bushwillow
          - type: thermostat
            entity: climate.nick_s_device
            name: Nick's AC
          - show_current: true
            show_forecast: false
            type: weather-forecast
            entity: weather.gordons_bay
            name: Gordons Bay
          - square: true
            type: grid
            cards:
              - type: entities
                entities:
                  - entity: sensor.gordons_bay_cloud_ceiling
                  - entity: sensor.gordons_bay_precipitation
                  - entity: sensor.gordons_bay_realfeel_temperature
                  - entity: sensor.gordons_bay_wind
                  - entity: sensor.gordons_bay_pressure_tendency
                  - entity: weather.gordons_bay
                title: Gordons Bay
            columns: 1
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.nicks_bedside_lamp
            icon: mdi:floor-lamp-outline
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.lexis_bedside_lamp_mijia_bedside_lamp_sw_auth
            icon: mdi:floor-lamp-outline
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_1000743d1b
            icon: mdi:television
            name: Bedroom TV
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            icon: mdi:desk-lamp
            entity: light.midesklamp1s_7a18
            name: Office
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            icon: mdi:light-flood-down
            name: Pool
            entity: switch.sonoff_1000f3bba5_2
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_1000f3bba5_3
            icon: mdi:pool
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_1000f3bba5_1
            icon: mdi:pool
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_100100d655_2
            icon: mdi:track-light
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_100100d655_1
            icon: mdi:light-recessed
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_100100d655_3
            name: Lounge
            icon: mdi:dome-light
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_1001195031_1
            name: Dining Room
            icon: mdi:dome-light
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_1001195031_2
            name: Kitchen
            icon: mdi:dome-light
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_10011a5696
            name: Guest Bathroom
            icon: mdi:dome-light
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.sonoff_1001195799_2
            name: Entrance
            icon: mdi:dome-light
            show_state: false
